version: '3'
services:
  kanboard:
    build:
      dockerfile: ./Dockerfile/Dockerfile
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
    environment:
      - DB_DRIVER=postgres
      - DB_USERNAME=kanboard
      - DB_PASSWORD=password
      - DB_HOSTNAME=db
      - DB_NAME=kanboard
    depends_on:
      - db

  db:
    image: postgres:10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kanboard
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kanboard
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:
  postgres_data:
