apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./ingress.yaml
  - ./letsencrypt.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  # Url kanboard (for ingress controller
  - name: ingress-kanboard-config
    behavior: create
    literals:
      - URL=kanboard.niernen.com # replace by the right value

vars:
  - name: URL
    objref:
      apiVersion: v1
      kind: ConfigMap
      name: ingress-kanboard-config
    fieldref:
      fieldpath: data.URL
