name: ci

on:
  push:
    branches: main

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set version
        id: version
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Build and push
        uses: docker/build-push-action@v1.1.2 # I prefer this version
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/kanboard
          path: .
          dockerfile: ./Dockerfile/Dockerfile.buster
          push: true
          tags: buster-${{ steps.version.outputs.sha8 }}, latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-push
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set version
      id: version
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.6.1"
    - name: Update Kubernetes resources
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        VERSION: ${{ steps.version.outputs.sha8 }}
      run: |
       cd k8s/bases/
       kustomize edit set image kanboard=$DOCKERHUB_USERNAME/kanboard:buster-$VERSION
       cat kustomization.yaml
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Bump docker tag"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
